version: '3.2'

services:
  proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'proxy'
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: 'letsencrypt'
    restart: always
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=proxy
      - NGINX_PROXY_CONTAINER=proxy
      - DEFAULT_EMAIL=underpenguin424@gmail.com
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  underpenguin:
    container_name: underpenguin
    build: 
      context: .
      dockerfile: Dockerfile          
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VIRTUAL_HOST=underpenguin.com
      - LETSENCRYPT_HOST=underpenguin.com      

  volumes:
    certs:
    html:
    vhostd:

  networks:
    default:
      external:
        name: nginx-proxy